version: '3.0'
services:
  web:
    build: ./Magento
    ports:
      - "8888:80"
    links:
      - db
    env_file:
      - .env
    volumes:
      - ./..:/var/www/html/vendor/emartech/emarsys-magento2-extension
      - ./php.ini:/usr/local/etc/php/php.ini
    command: ["/opt/wait-for-it.sh", "db:3306", "--", "/sbin/my_init"]
  db:
    image: healthcheck/percona
    restart: always
    volumes:
      - magento-db:/var/lib/mysql
      - ./uninstall-extension.sql:/opt/uninstall-extension.sql
      - ./magento.sql:/opt/magento.sql
    ports:
      - "13306:3306"
    env_file:
      - .env
  node:
    image: "node:9.11.1-alpine"
    links:
      - db
    user: "node"
    working_dir: /test
    env_file:
      - .env
    volumes:
      - ./test:/test
    expose:
      - "8081"
    command: "npm i"
volumes:
  magento-db: