version: '3.0'
services:
  web:
    image: eu.gcr.io/ems-plugins/magento-sampledata:2.2.3
    ports:
      - "8888:80"
    links:
      - db
    env_file:
      - .env
    volumes:
      - ./Magento/composer.json:/app/composer.json
      - ./..:/app/vendor/emartech/emarsys-magento2-extension
      - ./setup:/opt/emartech/setup
      - ./php.ini:/opt/docker/etc/php/php.ini
    command: ["/opt/emartech/wait-for-it.sh", "db:3306", "--timeout=30", "--strict", "--", "/opt/emartech/init"]
  db:
    image: healthcheck/percona
    restart: always
    volumes:
      - magento-db:/var/lib/mysql
      - ./uninstall-extension.sql:/opt/uninstall-extension.sql
    ports:
      - "13306:3306"
    env_file:
      - .env
  node:
    container_name: mage_node
    build:
      context: .
      dockerfile: ./Docker/Dockerfile-node
      args:
        - NPM_TOKEN=$NPM_TOKEN
    volumes:
      - ./test:/projectroot/test
    env_file:
      - .env
    links:
      - web:magento.local
      - db
volumes:
  magento-db:
