version: '3.0'
services:
  web:
    image: alexcheng/magento2
    ports:
      - "8888:80"
    links:
      - db
    env_file:
      - .env
    volumes:
      - ./..:/var/www/html/vendor/emartech/emarsys-magento2-extension
      - ./composer.json:/var/www/html/composer.json
  db:
    image: percona
    restart: always
    volumes:
      - magento-db:/var/lib/mysql
    ports:
      - "13306:3306"
    env_file:
      - .env
volumes:
  magento-db: